name: "Create .env.local"
description: "Create a .env.local file and populate it with secrets"

inputs:
  coingecko_api_key:
    description: "Coingecko API Key"
    required: false
  near_node_url:
    description: "Near Node URL"
    required: false
  wallet_connect_project_id:
    description: "Project ID key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create .env.local
      shell: bash
      run: |
        if [[ -n "${{ inputs.coingecko_api_key }}" ]]; then
          echo COINGECKO_API_KEY=${{ inputs.coingecko_api_key }} >> .env.local
        fi
        if [[ -n "${{ inputs.near_node_url }}" ]]; then
          echo NEAR_NODE_URL=${{ inputs.near_node_url }} >> .env.local
        fi
        if [[ -n "${{ inputs.wallet_connect_project_id }}" ]]; then
          echo WALLET_CONNECT_PROJECT_ID=${{ inputs.wallet_connect_project_id }} >> .env.local
        fi
